### PR TITLE
Use the SocketError superclass constructor as the main export

### PR DESCRIPTION
**Pull request by papandreou**
Also, replace the NotSocketError class with a static `supports` method.

Here is how it'd be integrated in teepee: https://github.com/One-com/teepee/commit/86ca37e3378209c461d185adc9a28d2af9bbbe6f

### CODE REVIEW

**Comment by papandreou** [comment]
@alexjeffburke Did you arrive at a conclusion wrt. this?

**Comment by alexjeffburke** [comment]
@papandreou this totally fell off my radar ..let me look at it again and I'll get you a more concrete answer soon :)

**Comment by papandreou** [comment]
I'm using a fork for now, so take your time :)

**Comment by alexjeffburke** [comment]
This PR was landed as f1c1f11ef895c955877d62a6c37b5d65a7fdb0cd. As of release `0.3.0` the library support this syntax while also retaining backwards compatibility with earlier versions.

**Pull request closed without merging**
